[project]
name = "freedomagent-smartyoga-content"
version = "0.1.0"
description = "A SmartYoga Content Agent"
authors = ["Your Name <your@email.com>"]
dependencies = [
    "crewai>=0.22.8",
    "openai",
    "python-dotenv"
]
requires-python = ">=3.10"

[tool.crew]
entrypoint = "src.crew:crew"
