[project]
name = "freedomagent-smartyoga-content"
version = "0.1.0"
description = "CrewAI agent for SmartYoga daily content"
authors = [{name = "Your Name"}]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
